/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileSystem: typeof import('./src/components/FileSystem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    VsCodeFileExplorer: typeof import('./src/components/VsCodeFileExplorer.vue')['default']
    VsCodeFIleExplorer: typeof import('./src/components/VsCodeFIleExplorer.vue')['default']
    VsCodeIde: typeof import('./src/components/VsCodeIde.vue')['default']
    VsCodeMonacoEditor: typeof import('./src/components/VsCodeMonacoEditor.vue')['default']
    VsCodeTerminal: typeof import('./src/components/VsCodeTerminal.vue')['default']
    WcFileSystem: typeof import('./src/components/WcFileSystem.vue')['default']
    WcIde: typeof import('./src/components/WcIde.vue')['default']
    WcMonacoEditor: typeof import('./src/components/WcMonacoEditor.vue')['default']
    WcTerminal: typeof import('./src/components/WcTerminal.vue')['default']
  }
}
